version: '3'

services:
  frontend:
    image: ghcr.io/jaimcamp/gt-explorer/gtexplorer-frontend:latest
    #build: frontend
    ports:
      - 9501:8501
    depends_on:
      - backend
    volumes:
      - ./storage:/storage
  backend:
    image: ghcr.io/jaimcamp/gt-explorer/gtexplorer-backend:latest
    #build: backend
    ports:
      - 9080:8080
    volumes:
      - ./storage:/storage
